### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by ravensborn** [kagan94/CRM-Dentistry-online#2]
Gives this error when I try to run the index.php

Warning: require_once(C:\xampp\htdocs\a/../../../../yii/framework/yii.php): failed to open stream: No such file or directory in C:\xampp\htdocs\a\index.php on line 12

Fatal error: require_once(): Failed opening required 'C:\xampp\htdocs\a/../../../../yii/framework/yii.php' (include_path='C:\xampp\php\PEAR') in C:\xampp\htdocs\a\index.php on line 12

**Comment by kagan94** [comment]
Folder "/framework/*" was missing in the project, I've just added it.
Please check again.

**Comment by ravensborn** [comment]
I still cannot access any of the pages.

![image](https://user-images.githubusercontent.com/27031143/95867431-d0c57880-0d71-11eb-94a9-b468e459c36e.png)
